fix: Failed to fetch documents when pub-manifest file has no file name extension
e.g., `<link rel="publication" href="./manifest">` causes
Error: Failed to fetch a source document from… (404 Not Found)