fix: typescript error TS2612: Property 'xxx' will overwrite the base property
Updating typescript from 4.2 to 4.3 causes the error TS2612: Property 'xxx' will overwrite the base property,

> Error: /vivliostyle.js/packages/core/src/vivliostyle/css-parser.ts(519,3): semantic error TS2612: Property 'flavor' will overwrite the base property in 'ParserHandler'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

> Error: /vivliostyle.js/packages/core/src/vivliostyle/layout.ts(469,3): semantic error TS2612: Property 'computedBlockSize' will overwrite the base property in 'Container'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

etc.