chore: bump gulp-sass from 4 to 5
This fixes problem that vivliostyle-viewer build failed on arm64 mac
with the node-sass error:
Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93)

Now moved from the deprecated "node-sass" to "sass" (Dart Sass)