chore: update deps (yarn upgrade)
Note: Due to the update of typescript (4.3.5 to 4.4.3), the following build error occurred and needed to fix
Error: /Users/shinyu/viv/vivliostyle.js/packages/core/src/vivliostyle/task.ts(152,22): semantic error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'Error'.
  Type '{}' is missing the following properties from type 'Error': name, message