fix(react): Fix code that causes null error
containerRef.current is null because it was removed from the DOM tree during the cleanup function call.
This is a follow-up to a change in React17.

The following error occurred during a page transition.
TypeError: Cannot set properties of null (setting 'innerHTML')